### PR TITLE
Model optimization 2

### PR DESCRIPTION
**Pull request by Braiam23**
## 🤔 What type of PR is this? (check all applicable)

- [X] 🍕 Addition
- [ ] ⌨️ Productivity
- [X] 🐛 Bug Fix
- [X] 🔥 Optimization
- [ ] ⚙️ Configuration
- [X] 🌟 Quality Of Life
- [X] ✨ Enhancement
- [ ] 📝 Documentation

## 🎯 Key Objectives

The goal is to optimize most models whether old or new, with the intention of reducing the size of the mod and the ease of loading the mod.

## 🚦 Testing 

The changes have been tested by groups of models and no model has been negatively affected

## 📖 Added to documentation?

- [ ] 📜 README.md
- [ ] 📓 Javadoc
- [ ] 🍕 Comments
- [X] 🙅 no documentation needed

### CODE REVIEW

**Comment by Braiam23** [comment]
Fixed

**Comment by Desoroxxx** [comment]
Will test and merge tomorrow

**Comment by Braiam23** [comment]
ok

**Comment by Braiam23** [comment]
Fixed now

**Comment by Braiam23** [comment]
bruh

**Comment by Braiam23** [comment]
any other problem?

**Comment by Desoroxxx** [comment]
> any other problem?

Look at Discord

**Comment by Braiam23** [comment]
.__×__.

**Comment by Desoroxxx** [comment]
Weapons are still very close to the camera

**Comment by Braiam23** [comment]
um... wait let me think

**Pull request closed without merging**
