### PR TITLE
Change GL ammo back to 64

### PR DESCRIPTION
**Pull request by strubium**

### CODE REVIEW

**Review by SticksDeveloper — APPROVED** [review]
Looks good to me

**Comment by Desoroxxx** [comment]
Why?

**Comment by strubium** [comment]
> Why?

It's not at a point where I should start "balancing" it

**Comment by Desoroxxx** [comment]
I think 16 is a good balance as normal grenade stack size are 1, so that means you can already have 16 times more grenade if you use a launcher for them which is already powerful enough

**Comment by strubium** [comment]
Maybe

**Comment by Paneedah** [comment]
I do not believe that this change would be beneficial. Grenade launcher ammo stacking to 64 makes no sense. I might consider switching it to 8 or 16 at the very most.

**Pull request closed without merging**
