### PR TITLE
Add snow bullet SFX

### PR DESCRIPTION
**Pull request by strubium**
## 🤔 What type of PR is this? (check all applicable)

- [x] 🍕 Addition
- [ ] ⌨️ Productivity
- [ ] 🐛 Bug Fix
- [ ] 🔥 Optimization
- [ ] ⚙️ Configuration
- [ ] 🌟 Quality Of Life
- [ ] ✨ Enhancement
- [ ] 📝 Documentation

## 📝 Description

This adds a (Fair use) sound effect for Snow and Crafted Snow.

## 🧐 The Rationale

MWC reuses lots of sound effects, which leads to "sound fatigue" of the players. This adds a new sound effect to spice it up a little. 

## 🎯 Key Objectives

- Add bullet_14_snow
- Add MaterialImpactSound for Crafted Snow

## 🚦 Testing

I have not tested this yet! 

## ⏮️ Backwards Compatibility 

1.12.2

## 📚 Related Issues & Documents

N/A

## 🖼️ Screenshots/Recordings

Will provide when i test my changes

## 📖 Added to documentation?

- [ ] 📜 README.md
- [ ] 📓 Javadoc
- [ ] 🍕 Comments
- [x] 🙅 no documentation needed

### CODE REVIEW

**Comment by Paneedah** [comment]
Can we have you please test this and show a video of what it sounds like?

Thanks!

**Comment by strubium** [comment]
> Can we have you please test this and show a video of what it sounds like?
> 
> Thanks!

Yep! Once I get back to my PC I'll send the recording.

**Comment by strubium** [comment]
@Paneedah Done! Check #contribution-team as this video is too big for GitHub

**Comment by strubium** [comment]
[2023-11-01_17-15-49.zip](https://github.com/Cubed-Development/Modern-Warfare-Cubed/files/13291065/2023-11-01_17-15-49.zip)

**Comment by Paneedah** [comment]
Looks good to me, leaving for review for @Desoroxxx.

**Comment by Desoroxxx** [comment]
GitHub is being reworked, please reopen this pull request once finished, will update on Discord once the rework is done.

**Pull request closed without merging**
