### PR TITLE
Added support for custom skins. Tested with 0 performance impacts.

### PR DESCRIPTION
**Pull request by Paneedah**
Unfortunately has to be a janky implementation due to `Minecraft.getMinecraft()` being null during pre-init, which, Dynamic Resources require the Minecraft instance.

Note: Servers will also need the images in order to register.

### CODE REVIEW

**Comment by Desoroxxx** [comment]
> Unfortunately has to be a janky implementation due to `Minecraft.getMinecraft()` being null during pre-init, which, Dynamic Resources require the Minecraft instance.

`Minecraft.getMinecraft()` is never null during pre-init, `Minecraft` get initialized first thing in the whole code, without it the game does absolutely nothing.

**Comment by Paneedah** [comment]
Then complain to the nullpointer i was getting not to me xD

**Comment by Desoroxxx** [comment]
> Then complain to the nullpointer i was getting not to me xD

It is probably because you where using it on the server then, `Minecraft` is the physical client class

**Comment by Desoroxxx** [comment]
Holy, please only run the actual texture registering, on the client, you are doing it on both sides right now

**Pull request merged**
