### PR TITLE
Optimization models 

### PR DESCRIPTION
**Pull request by Braiam23**
## 🤔 What type of PR is this? (check all applicable)

- [X] 🍕 Addition
- [ ] ⌨️ Productivity
- [X] 🐛 Bug Fix
- [X] 🔥 Optimization
- [ ] ⚙️ Configuration
- [X] 🌟 Quality Of Life
- [X] ✨ Enhancement
- [ ] 📝 Documentation

## 🎯 Key Objectives

The goal is to optimize most models whether old or new, with the intention of reducing the size of the mod and the ease of loading the mod.
In this pull request now it works with the last changes of the mod and meets requested cam and recoil changes
## 🚦 Testing 

The changes have been tested by groups of models and some models depending on the weapon suffer visual bugs if the models are edited, some java models are maintained

## 📖 Added to documentation?

- [ ] 📜 README.md
- [ ] 📓 Javadoc
- [ ] 🍕 Comments
- [X] 🙅 no documentation needed

# take your time if you want to supervise

### CODE REVIEW

**Comment by Braiam23** [comment]
thanks to Koud _Wind for reviewing and mentioning the possible problems that are already solved

**Comment by Braiam23** [comment]
can I merge the pull request?

**Comment by Desoroxxx** [comment]
No you cannot, but I can after I slept

**Comment by Braiam23** [comment]
Demonios, ya estoy perdiendo la paciencia

**Comment by Desoroxxx** [comment]
> Hell, I'm already losing patience Well, just wait

Calm down, it changes nothing whether I merge this now or in 9 hours.
I am too tired to review and test this now so I will do after I slept

**Comment by Braiam23** [comment]
> Calm down, it changes nothing whether I merge this now or in 9 hours. I am too tired to review and test this now so I will do after I slept

okey, good night

**Comment by Desoroxxx** [comment]
image

The AAC Honey Badge silencer is completely broken:
- It is not positioned correctly in the GUI
- It cannot be removed

**Comment by Braiam23** [comment]
> image
> 
> The AAC Honey Badge silencer is completely broken:
> 
> * It is not positioned correctly in the GUI
> * It cannot be removed

Fix

**Comment by Braiam23** [comment]
some other bug, because I have tried almost everything and there are no bugs

**Comment by Desoroxxx** [comment]
Please add to the changelog that you added variant of the deagle for black and gold

**Comment by Desoroxxx** [comment]
Don't worry about the merge conflict it is very easy to fix and should only be fixed right before merging otherwise you will not be able to run this branch

**Comment by Desoroxxx** [comment]
image
image

**Comment by Desoroxxx** [comment]
Directed by Robert B. Weide

**Comment by Desoroxxx** [comment]
Also, stop merging master branches into your branches, it only causes problems, merge conflicts should only be resolved when merging.

**Comment by Desoroxxx** [comment]
Please stop touching that file

**Comment by Braiam23** [comment]
do i revert the changes?

**Comment by Braiam23** [comment]
> Also, stop merging master branches into your branches, it only causes problems, merge conflicts should only be resolved when merging to master.

that does it automatically I don't know how it is accepted

**Comment by Braiam23** [comment]
first I downloaded the modified file (attachments.java) from the main branch and move the additions/changes from the old file to the new one, you have an image that no longer has the problem

**Comment by Braiam23** [comment]
image

**Comment by Braiam23** [comment]
image

**Comment by Braiam23** [comment]
where do so many problems come from? literally the optimized models have the same code as the old models

**Comment by Desoroxxx** [comment]
> where do so many problems come from? literally the optimized models have the same code as the old models

You also changed factories and no, if they had the same code nothing would have changed lol

**Comment by Braiam23** [comment]
I was referring to the imports, the factoys are the lod that are close to having bugs :v

**Pull request merged**
