### PR TITLE
Fixing issue #82, and starting on freeing weapons from the Compatibility Layer.

### LINKED ISSUE #82: Incorrect Bounding Box for the Workbench
## Describe the bug

The workbench currently does not override the default bounding box. Given that the workbench is larger than a single block, this results in an inaccurate bounding box. This discrepancy is not just problematic in terms of collision detection, but also affects rendering. Specifically, the workbench disappears as soon as the bounding box is not within the frustum. This issue needs to be addressed to correct both the collision and rendering behaviors.

## Screenshots or/and videos

image

### PR DESCRIPTION
**Pull request by azuraerae**
This will close #82!

### CODE REVIEW

**Comment by azuraerae** [comment]
@Desoroxxx

**Comment by Desoroxxx** [comment]
Please separate this in two pr's

**Comment by Paneedah** [comment]
Doesn't need to be 2 PR's, I'm happy to merge this.

**Comment by Desoroxxx** [comment]
> Doesn't need to be 2 PR's, I'm happy to merge this.

No, half of it is wrong

**Comment by Desoroxxx** [comment]
Guess I will fix it myself

**Pull request merged**
