### PR TITLE
Recoil cleaning & Add horizontal recoil

### PR DESCRIPTION
**Pull request by Koud-Wind**
## 🤔 What type of PR is this? (check all applicable)

- [x] 🍕 Addition
- [ ] ⌨️ Productivity
- [ ] 🐛 Bug Fix
- [x] 🔥 Optimization
- [x] ⚙️ Configuration
- [x] 🌟 Quality Of Life
- [x] ✨ Enhancement
- [ ] 📝 Documentation

## 📝 Description
Clean up the recoil properties of accessories
Change the way weapons read recoil
Add horizontal recoil
Slightly clean the balance package code

## 🚦 Testing 
 - [x] Client
 - [ ] Server

## ⏮️ Backwards Compatibility 
Perhaps it has reduced the scalability of modifying weapon attributes for accessories
Removed a byteBuf.readFloat(), which may result in incorrect weapon data (When the byte data of a weapon in NBT is incorrect, it has a very low probability of collapse)

## 🖼️ Screenshots/Recordings
image

### CODE REVIEW

**Comment by Desoroxxx** [comment]
Weapon System Version 1 is deprecated, in version 2 recoil is the strength applied to the recoil pattern

**Comment by Desoroxxx** [comment]
> > Weapon System Version 1 is deprecated, in version 2 recoil is the strength applied to the recoil pattern
> 
> What should I do? Which class is related to

You don't need to do anything horizontal recoil is already a thing in the mod

**Comment by Koud-Wind** [comment]
> You don't need to do anything horizontal recoil is already a thing in the mod

Do you mean from WeaponFireAspect.fire?

**Comment by Desoroxxx** [comment]
> > You don't need to do anything horizontal recoil is already a thing in the mod
> 
> Do you mean from WeaponFireAspect.fire? I really want to know what the problem is with this branch Did you just say RecoilParam?

There is no real problem, it's just unnecessary, you basically misunderstood the recoil system

**Comment by Koud-Wind** [comment]
The recoil of the weapon should not be in the NBT, otherwise players will not update it when loading the balance pack, The backseat should only change the player's perspective, while RecoilParam only changes the jitter during weapon rendering. It does not change the player's perspective, and the code in WeaponFireAspect.fire truly modifies the player's perspective

**Comment by Koud-Wind** [comment]
The recoil of the weapon should not be in the NBT, otherwise players will not update it when loading the balance pack, The backseat should only change the player's perspective, while RecoilParam only changes the jitter during weapon rendering. It does not change the player's perspective, and the code in WeaponFireAspect.fire truly modifies the player's perspective

**Comment by Desoroxxx** [comment]
> The recoil of the weapon should not be in the NBT, otherwise players will not update it when loading the balance pack, The backseat should only change the player's perspective, while RecoilParam only changes the jitter during weapon rendering. It does not change the player's perspective, and the code in WeaponFireAspect.fire truly modifies the player's perspective

Anyway, you misunderstood how the recoil system work, the `recoil` value of a weapon is a multiplier to the recoil, not the recoil itself, we already have horizontal and vertical recoil it's in fact a whole pattern that can be changed, somewhat like in Counter Strike.

Currently balance packs do not allow you to change said pattern, but again putting effort on balance packs is essentially a waste of time as they are going to be replaced by experience packs in a future dedicated update.

**Comment by Koud-Wind** [comment]
> Currently balance packs do not allow you to change said pattern, but again putting effort on balance packs is essentially a waste of time as they are going to be replaced by experience packs in a future dedicated update.

Can you add me on trello?

**Comment by Desoroxxx** [comment]
> Can you add me on trello? (KoudWind)

It's public

**Comment by Koud-Wind** [comment]
> It's public

I know it's public

**Pull request closed without merging**
