### PR TITLE
Cleaning Factory Files

### PR DESCRIPTION
**Pull request by Braiam23**
It consists of eliminating unnecessary lines of code or that do not affect the configuration

## 🤔 What type of PR is this? (check all applicable)

- [ ] 🍕 Addition
- [ ] ⌨️ Productivity
- [ ] 🐛 Bug Fix
- [X] 🔥 Optimization
- [ ] ⚙️ Configuration
- [ ] 🌟 Quality Of Life
- [ ] ✨ Enhancement
- [ ] 📝 Documentation

## 📝 Description

It consists of eliminating unnecessary lines of code or that do not affect the configuration

## 🎯 Key Objectives
Perform an optimization of the factories files, clean unnecessary code

## 📖 Added to documentation?

- [ ] 📜 README.md
- [ ] 📓 Javadoc
- [ ] 🍕 Comments
- [X] 🙅 no documentation needed

### CODE REVIEW

**Comment by Braiam23** [comment]
Almost everything is ready, you need to give it a test and it will be ready for the pull request, don't accept the pull yet

**Comment by Braiam23** [comment]
ok I think everything is ready, I already put them to the test, current photos:

**Comment by Desoroxxx** [comment]
Will test and merge tomorrow

**Comment by Braiam23** [comment]
I'm going to fix that tomorrow

**Comment by Braiam23** [comment]
I think it is ready

**Pull request closed without merging**
