### PR TITLE
Removed - Props | Turrets, Fixed AnimationGUI warnings

### PR DESCRIPTION
**Pull request by SticksDeveloper**
Merged Props | Turrets removal with Master.

### CODE REVIEW

**Comment by Desoroxxx** [comment]
Again we are not removing turrets

**Comment by Paneedah** [comment]
Why aren't we removing turrets? They have to be redone completely alongside all other entities that need an overhaul. Turrets do not currently work. Either remove them for now or fix them asap as I don't want broken features that everyone complains about enabled.

**Comment by Desoroxxx** [comment]
> Why aren't we removing turrets? They have to be redone completely alongside all other entities that need an overhaul. Turrets do not currently work. Either remove them for now or fix them asap as I don't want broken features that everyone complains about enabled.

Well we can disable them completely once someone works on the config system.

There is also no point to remove them now, to then re add them later, to then finally fix them, instead of spending time tracking down every little bit of code and files to remove them why not fix them/ improve them

**Comment by SticksDeveloper** [comment]
> Reference

There's a chance by then It will be moved to an entirely different mod with the Improved version of It.

**Comment by Desoroxxx** [comment]
> > Reference
> 
> There's a chance by then It will be moved to an entirely different mod with the Improved version of It.

No, we are not making another mod:

MWC
MWC Props

That's it MWC arcade stuff will go in the main mod when they come back but as a config

**Comment by strubium** [comment]
I think it should be its own mod for combability with IE

**Comment by Desoroxxx** [comment]
> I think it should be its own mod for combability with IE

That is not related

**Comment by strubium** [comment]
> That is not related

Are you sure? The turrets are in such a broken state that at the very least a config for disabling them is urgently needed.

IE adds turrets, and MWC working with them would be nice. Come to think of it, IE crusher support would also be really cool.

**Comment by Desoroxxx** [comment]
> > That is not related
> 
> Are you sure? The turrets are in such a broken state that at the very least a config for disabling them is urgently needed.

What do you mean broken, they are not broken they just don't have the function to recognize or shoot the enemies.

> IE adds turrets, and MWC working with them would be nice. Come to think of it, IE crusher support would also be really cool.

Yeah that is not related to the discusion

**Comment by strubium** [comment]
> What do you mean broken, they are not broken they just don't have the function to recognize or shoot the enemies.

They are REALLY stupid, failing to see and shoot most mobs and players.    

> Yeah that is not related to the discussion

I'll make another one, sorry

**Comment by Desoroxxx** [comment]
> They are REALLY stupid, failing to see and shoot most mobs and players.

What? The actual system for them to see and shoot mobs and players does not exist currently obviously they are going to fail at a task they are not capable of doing.

If I ask you to fly and you deny, you are not broken it is simply something you cannot do.

**Comment by SticksDeveloper** [comment]
Girls Girls, Chill out

**Comment by Desoroxxx** [comment]
What the heck "too heated"...

Have you been outside, this is just a conversation no one was insulting no one???

**Comment by strubium** [comment]
> > They are REALLY stupid, failing to see and shoot most mobs and players.
> 
> What? The actual system for them to see and shoot mobs and players does not exist currently obviously they are going to fail at a task they are not capable of doing.

Exactly, broken af

**Comment by Desoroxxx** [comment]
> Exactly, broken af

Sorry what is broken?

As far as I know you can't really break air can you?

**Comment by strubium** [comment]
The "actual system for them to see and shoot mobs and players does not exist", therefore, the turret ai is broken

**Comment by Desoroxxx** [comment]
> The "actual system for them to see and shoot mobs and players does not exist", therefore, the turret ai is broken

How can it be broken if it does not exist?

**Comment by strubium** [comment]
No, the turrets are broken.

**Comment by strubium** [comment]
> What? The actual system for them to see and shoot mobs and players does not exist currently obviously they are going to fail at a task they are not capable of doing.

**Comment by coosencake** [comment]
> > I would say that turrets should actually shoot hostile's
> 
> I would say that this mod is not in a release state, it's in beta, some features will be missing.

I would say that a turret that cant identify or shoot people isn't a turret.

**Comment by WillStephens27** [comment]
What kind of idiot would waste their time coding some dumb furry website or app? They're probably a bunch of lonely losers who have nothing better to do with their lives. I mean, come on, who in their right mind would want to dress up like an animal and pretend to be one? It's so pathetic and sad. They're probably all a bunch of virgins who can't get a date in real life, so they have to hide behind their stupid furry avatars. I hope they all get banned from the internet and have to go back to living in their parents' basements.

**Comment by SticksDeveloper** [comment]
> What kind of idiot would waste their time coding some dumb furry website or app? They're probably a bunch of lonely losers who have nothing better to do with their lives. I mean, come on, who in their right mind would want to dress up like an animal and pretend to be one? It's so pathetic and sad. They're probably all a bunch of virgins who can't get a date in real life, so they have to hide behind their stupid furry avatars. I hope they all get banned from the internet and have to go back to living in their parents' basements.

bro I'm 1. not a furry 2. this is fucking github

**Comment by strubium** [comment]
> you furrys are a delusional, pathetic, sick pervert who should be ashamed of their disgusting hobby. They probably can't even get a date in real life and that's why they have to hide behind a stupid animal costume. If that doesn't work, your friend should just tell them to go fuck themselves and move on with their life. Don't waste your time arguing with those freaks.

bros mad

**Comment by SticksDeveloper** [comment]
> > you furrys are a delusional, pathetic, sick pervert who should be ashamed of their disgusting hobby. They probably can't even get a date in real life and that's why they have to hide behind a stupid animal costume. If that doesn't work, your friend should just tell them to go fuck themselves and move on with their life. Don't waste your time arguing with those freaks.
> 
> bros mad

fr

**Comment by coosencake** [comment]
"bro I'm 1"

**Comment by SticksDeveloper** [comment]
> "bro I'm 1"

fr

**Pull request closed without merging**
