### PR TITLE
Overhaul M40A6 Animation & Overhaul 100 Rounds NATO Drum Magazine, Aimpoint Comp M5 Sight Models and Textures

### PR DESCRIPTION
**Pull request by Braiam23**
Now the animation and sound effects of the m40a6 have been fixed again xD, I made a mess of the old repository

## 🤔 What type of PR is this? (check all applicable)

- [X] 🍕 Addition
- [ ] ⌨️ Productivity
- [ ] 🐛 Bug Fix
- [ ] 🔥 Optimization
- [ ] ⚙️ Configuration
- [ ] 🌟 Quality Of Life
- [X] ✨ Enhancement
- [ ] 📝 Documentation

## 📖 Added to documentation?

- [ ] 📜 README.md
- [ ] 📓 Javadoc
- [ ] 🍕 Comments
- [X] 🙅 no documentation needed

## Test photo or video

https://github.com/Cubed-Development/Modern-Warfare-Cubed/assets/133471454/e5a22179-e23d-46ef-a952-a004099bc0f4

## Objective

Improve the broken animation of the m40a6 and test if you can renew the models of the scopes(Aimpoint Comp M5) at the same time try to reduce the size of the model files

### CODE REVIEW

**Comment by Braiam23** [comment]
Ready now if I try to fix as much as I can for the animations

**Comment by Desoroxxx** [comment]
Amazing you fixed nearly all of it there is one last clipping when the bolt is moved for the unload animation

**Comment by Braiam23** [comment]
> Amazing you fixed nearly all of it there is one last clipping when the bolt is moved for the unload animation


https://github.com/Cubed-Development/Modern-Warfare-Cubed/assets/133471454/1457c1ab-4ab5-44d0-bfc2-759f64e8da3c

**Comment by Braiam23** [comment]
all bolt action settings are replicated in all animations

**Pull request merged**
