### PR TITLE
Fix button error

### PR DESCRIPTION
**Pull request by Koud-Wind**

### CODE REVIEW

**Comment by Desoroxxx** [comment]
What does this fix exactly?

**Comment by Desoroxxx** [comment]
Please hurry up :trollface:

**Comment by Koud-Wind** [comment]
https://github.com/Cubed-Development/Modern-Warfare-Cubed/issues/156

**Comment by Koud-Wind** [comment]
So did you forget to add it or intentionally delete it? This is the statement included in the previous version

**Comment by Desoroxxx** [comment]
> So did you forget to add it or intentionally delete it? This is the statement included in the previous version

?

**Comment by Koud-Wind** [comment]
This is not something I added myself, it was included in the previous development version

**Comment by Koud-Wind** [comment]
If you are not aware that this statement was previously included, please add it
image

**Pull request closed without merging**
