### PR TITLE
Fix crash

### PR DESCRIPTION
**Pull request by Koud-Wind**
When the player is set velocity, the server will crash
I may be too anxious

### CODE REVIEW

**Comment by Paneedah** [comment]
Can you for the love of god follow the PR template? I have literally 0 information on this issue and what exactly it fixes. Also provide more detail in the name of the PR.

**Comment by Koud-Wind** [comment]
> Can you for the love of god follow the PR template? I have literally 0 information on this issue and what exactly it fixes. Also provide more detail in the name of the PR.

I made a mistake, it is different from https://github.com/Cubed-Development/Modern-Warfare-Cubed/pull/146 correlation

**Comment by Koud-Wind** [comment]
> Can you for the love of god follow the PR template? I have literally 0 information on this issue and what exactly it fixes. Also provide more detail in the name of the PR.

When the player is set velocity, the server will crash

**Comment by Desoroxxx** [comment]
> > Can you for the love of god follow the PR template? I have literally 0 information on this issue and what exactly it fixes. Also provide more detail in the name of the PR.
> 
> When the player is set velocity, the server will crash

Please provide a crash report

**Comment by Desoroxxx** [comment]
I will just redo that entire config on Monday

**Pull request closed without merging**
