### PR TITLE
hotfix on groovyscript/metadata/oredict

### PR DESCRIPTION
**Pull request by yor42**
## 📝 Description

This PR should fix Groovyscript-powered custom recipe system not accounting for oredict/metadate. this also fixes incorrect item name display when item has metadata.

## 🎯 Goals

  - Fix Groovyscript's ''removeAll'' method crashing on some edge cases
  - Fix incorrect Item name if ingredient has metadata
  - Fix recipe system breaking if recipe's ingredient has metadata or ingredient is oredict-based

## ❌ Non Goals

 - It is not a goal to overhaul the crafting system.
 - It is not a goal to remove old Json recipe system completely.

## 🚦 Testing 

```groovy
mods.mwc.craftingstation.removeAll()

mods.mwc.craftingstation.recipeBuilder().output(item('minecraft:iron_ingot')).input(item('immersiveengineering:metal', 2)*4).setYield(0.5).input(ore('ingotCopper')*4).register()
```

use this example script to test all 3 of changes.

## ⏮️ Backwards Compatibility 

has chance of breaking existing Json recipe, but groovy is much more human-readable and completely replaces, or even supersedes json, impact would be negligible. 

## 📚 Related Issues & Documents

N/A

## 🖼️ Screenshots/Recordings

image

image

image

## 📖 Added to documentation?

- [ ] 📜 README.md
- [ ] 📑 Documentation
- [ ] 📓 Javadoc
- [ ] 🍕 Comments
- [X] 🙅 No documentation needed

## 😄 [optional] What gif best describes this PR or how it makes you feel?

image

## Summary by CodeRabbit

- **New Features**
	- Introduced a more flexible crafting system with support for `Ingredient` over `Item`, enhancing crafting recipes and interactions.
	- Added a method to clear recipe registries, improving game performance and recipe management.
	- Enhanced GUI rendering for item display, providing a more intuitive user interface.

- **Bug Fixes**
	- Fixed client-side exposure decrease during game pause.
	- Addressed issues with spectators shooting weapons.
	- Corrected spawning positions of shells and bullet spawning math for increased accuracy.

- **Refactor**
	- Refactored ingredient handling across various classes for improved efficiency and readability.
	- Updated item handling and removal logic to use `Ingredient`, streamlining crafting operations.
	- Modified recipe display to better format and present crafting entries.

- **Documentation**
	- Updated changelog with recent fixes and enhancements, including Oredict support for the crafting system.

### CODE REVIEW

**Comment by Desoroxxx** [comment]
Haven't taken a complete look yet but does this retain ore dictionary compatibility for when it is implemented in the crafting stations logic?

**Comment by yor42** [comment]
if you are talking about json recipe, it works with existing Json recipes.
image

**Review by Desoroxxx — CHANGES_REQUESTED** [review]
Missing changelog entries, merge main into your branch and add changelog entries, and this can be merged.

**Review by Desoroxxx — APPROVED** [review]
LGTM

**Pull request merged**
