### PR TITLE
Fixed some issues with the M40a6

### PR DESCRIPTION
**Pull request by Braiam23**
## 🤔 What type of PR is this? (check all applicable)

- [ ] 🍕 Addition
- [ ] ⌨️ Productivity
- [X] 🐛 Bug Fix
- [ ] 🔥 Optimization
- [ ] ⚙️ Configuration
- [ ] 🌟 Quality Of Life
- [X] ✨ Enhancement
- [ ] 📝 Documentation

## 📝 Description
Fix all animation issues on the m40a6

## 🚦 Testing 
It is not necessary but in designer-progress there is progress

## 📖 Added to documentation?

- [ ] 📜 README.md
- [ ] 📓 Javadoc
- [ ] 🍕 Comments
- [X] 🙅 no documentation needed

### CODE REVIEW

**Comment by Desoroxxx** [comment]
Could you send a video of it?

**Comment by Braiam23** [comment]
> Could you send a video of it?

https://github.com/Cubed-Development/Modern-Warfare-Cubed/assets/133471454/b907be85-26f2-48a3-8e8b-0692c6fc8882

It's the closest thing to being able to fix it xD

**Comment by Desoroxxx** [comment]
This is already a huge improvement love it, but there still is some clipping on the reload animation do you think you can fix that, you fix it for the rest so it should be possible

**Comment by Braiam23** [comment]
> This is already a huge improvement love it, but there still is some clipping on the reload animation do you think you can fix that, you fixed it for the rest so it should be possible

;_; I would say yes but seriously it's a lot of work, his model is very broken, it wasn't easy to fix the boltaction of that weapon :"c

**Comment by Braiam23** [comment]
AHHH ACCEPT THE PULL REQUEST PLEASE

**Comment by Desoroxxx** [comment]
> AHHH ACCEPT THE PULL REQUEST PLEASE

Aren't you gonna fix the last bit of clipping?

**Comment by Braiam23** [comment]
> > AHHH ACCEPT THE PULL REQUEST PLEASE
> 
> Aren't you gonna fix the last bit of clipping?

From what second to what second does the problem occur?

**Comment by Desoroxxx** [comment]
> > > AHHH ACCEPT THE PULL REQUEST PLEASE
> > 
> > 
> > Aren't you gonna fix the last bit of clipping?
> 
> From what second to what second does the problem occur?

image

**Comment by Desoroxxx** [comment]
image

**Comment by Braiam23** [comment]
ok I will try to fix it but it is not exact it is very difficult

**Pull request closed without merging**
