### PR TITLE
Pink Camo remaster

### PR DESCRIPTION
**Pull request by strubium**

### CODE REVIEW

**Comment by Paneedah** [comment]
Could you send me a screenshot of what this looks like in-game?

**Comment by strubium** [comment]
Ight, let me build the mod

**Comment by Desoroxxx** [comment]
Also did you make this

**Comment by strubium** [comment]
I did, i used the base woodland camo and replaced the colors

**Comment by SticksDeveloper** [comment]
Looks good to merge tested It out

**Pull request merged**
