### PR TITLE
Add vest configs.  

### PR DESCRIPTION
**Pull request by strubium**
## 🤔 What type of PR is this? (check all applicable)

- [x] 🍕 Addition
- [ ] ⌨️ Productivity
- [ ] 🐛 Bug Fix
- [ ] 🔥 Optimization
- [x] ⚙️ Configuration
- [x] 🌟 Quality Of Life
- [x] ✨ Enhancement
- [ ] 📝 Documentation

## 📝 Description

Adds temp configs to change how much vest damage is reduced.

The coding is done, but I haven't tested it so stuff may break. I will test when I get home. 

## 🧐 The Rationale

Why you should add a vest damage config:

- The config will not be too bloated: This adds four configs in their own category. The only confing'ing the average user does is turn off the in-game shaders
- Stopgap while we wait for experience packs: Experience packs are probably gonna come in like 0.4 or something close. 
- Server owners need the config: The balance on my server is kinda wack at the moment. It would be nice to tweak vests.
- On your Trello, it doesn't even say you will be able to change the damage values of vests. (It's also in the Ideas/Future category) https://trello.com/c/g675KFwM/12-experience-pack        

## 🎯 Key Objectives

- Add configs
- Not break the mod

## 🚦 Testing 

Will test today when I get back to my house. 

## ⏮️ Backwards Compatibility 

1.12.2

## 📚 Related Issues & Documents

N/A

## 🖼️ Screenshots/Recordings

Will add when I get home.  

## 📖 Added to documentation?

- [ ] 📜 README.md
- [ ] 📓 Javadoc
- [ ] 🍕 Comments
- [x] 🙅 no documentation needed

### CODE REVIEW

**Comment by strubium** [comment]
Capture

A vest after being config'ed

**Comment by Desoroxxx** [comment]
No, this is something that experience packs will do, again too much config kill the config

**Comment by strubium** [comment]
> No, this is something that experience packs will do, again too much config kill the config

What do you that mean?

**Comment by Desoroxxx** [comment]
> > No, this is something that experience packs will do, again too much config kill the config
> 
> What do you mean?

Read again, and if you don't understand what experience packs are please go read the Trello card about them

**Comment by strubium** [comment]
> > > No, this is something that experience packs will do, again too much config kill the config
> > 
> > 
> > What do you mean?
> 
> Read again, and if you don't understand what experience packs are please go read the Trello card about them

I'm more confused about what you're referring to when you say "too much"? Can the config system not handle this many or are you talking about making the file bloated and hard to understand/modify?

And I did read the Trello card about it, where it says nothing about modifying equipment:
Experience pack should allow you to:

Disable any weapon

Disable any attachment
Disable any entity
Disable any vehicle
Disable any structure

Customize any weapon in depth

Customize any attachment in depth
Customize any entity in depth
Customize any vehicle in depth
Customize any structure in depth

I guess it could be under "Customize any entity" but that seems more like a NPC thing.

**Comment by strubium** [comment]
> image 

What does "Everything that is not mod wide" mean?

**Comment by Desoroxxx** [comment]
> > image
> 
> What does "Everything that is not mod wide" mean?

Changing the damage of a specific weapon is not mod wide.
Turning off the crafting system is mod wide.

Changing the damage reduction of a specific vest is not mod wide.
Changing the volume of weapons is mod wide.

Changing the speed of a specific vehicle is not mod wide.
Turning of shaders is mod wide.

**Pull request closed without merging**
