### PR TITLE
Optimization of old models

### PR DESCRIPTION
**Pull request by Braiam23**
## 🤔 What type of PR is this? (check all applicable)

- [X] 🍕 Addition
- [ ] ⌨️ Productivity
- [X] 🐛 Bug Fix
- [X] 🔥 Optimization
- [ ] ⚙️ Configuration
- [X] 🌟 Quality Of Life
- [X] ✨ Enhancement
- [ ] 📝 Documentation

## 🎯 Key Objectives

The goal is to optimize most models whether old or new, with the intention of reducing the size of the mod and the ease of loading the mod.

## 🚦 Testing 

The changes have been tested by groups of models and no model has been negatively affected

## 📖 Added to documentation?

- [ ] 📜 README.md
- [ ] 📓 Javadoc
- [ ] 🍕 Comments
- [X] 🙅 no documentation needed

It is still in progress they do not accept the pull resquet

### CODE REVIEW

**Review by Desoroxxx — CHANGES_REQUESTED** [review]
Missing Changelog

**Comment by Braiam23** [comment]
> Missing Changelog

ok

**Comment by Desoroxxx** [comment]
Are you still working on this, I see you did a pretty substantial commit 3 hour ago

**Comment by Braiam23** [comment]
> Are you still working on this, I see you did a pretty substantial commit 3 hour ago

Yes, I'm still working, I'm going to make one last commit and you accept the pull request

**Comment by Braiam23** [comment]
> Are you still working on this, I see you did a pretty substantial commit 3 hour ago

done, it's the last commit

**Comment by Braiam23** [comment]
there is a bug with the "AUG9mmCONVERSIONkit"

The file that should work is the "AUG9mmConversionkit" not the one with the name in Uppercase

**Comment by Desoroxxx** [comment]
> there is a bug with the "AUG9mmCONVERSIONkit"
> 
> The file that should work is the "AUG9mmConversionkit" not the one with the name in Uppercase image

Did you fix the bug?

**Comment by Braiam23** [comment]
> > there is a bug with the "AUG9mmCONVERSIONkit"
> > The file that should work is the "AUG9mmConversionkit" not the one with the name in Uppercase image
> 
> Did you fix the bug?

technically yes, because the file was added with the name in lowercase

**Comment by Braiam23** [comment]
image
ready accept the pull request please

**Review by Desoroxxx — APPROVED** [review]

**Pull request merged**
