### PR TITLE
Replace "Marine" Hud PNG with "Blank" Hud PNG

### PR DESCRIPTION
**Pull request by strubium**
## 🤔 What type of PR is this? (check all applicable)

- [ ] 🍕 Addition
- [ ] ⌨️ Productivity
- [x] 🐛 Bug Fix
- [ ] 🔥 Optimization
- [ ] ⚙️ Configuration
- [x] 🌟 Quality Of Life
- [ ] ✨ Enhancement
- [ ] 📝 Documentation

## 📝 Description
Title explains it very well, Most helmets have custom HUD images, but a lot reference the "Marine" png once used for spartan armor. I've added a new HUD texture named Blank that can be used instead.       

## 🧐 The Rationale
* Having a Blank Hud image is needed
* The Marine png can now be replaced with actual HUD stuff without breaking the other armors.    

## 🎯 Key Objectives
* Don't break the armor  

## 🚦 Testing 
I downloaded a copy of Marine.png and renamed it to Blank.png. It shouldn't require extensive testing unless there's a file that defines textures that I'm not aware of.    

## ⏮️ Backwards Compatibility 
I mean, its made for 1.12.2. Nothing below that.   

## 📚 Related Issues & Documents
N/A

## 📖 Added to documentation?

- [ ] 📜 README.md
- [ ] 📓 Javadoc
- [ ] 🍕 Comments
- [x] 🙅 no documentation needed

### CODE REVIEW

**Comment by Desoroxxx** [comment]
> Having a Blank Hud image is needed

I am pretty sure that it is not, a general rule for builders is to not have placeholders/blanks, just remove `.withHudTextureName("Marine")` but it will probably break since I guess it currently needs a texture, just change the code that requires a texture to not require one.

**Comment by Desoroxxx** [comment]
Wait, are you not using an IDE like IntelliJ?

**Comment by Desoroxxx** [comment]
> > Wait, are you not using an IDE like IntelliJ?
> 
> No, I'm coding from my school-issued Chromebook right now. I have IntelliJ on my desktop, but I cant easily bring it with me.

Oh, I would advise using IntelliJ for such task, as it will require testing to be done properly, I am unsure if it can run on a chromebook though.

**Comment by strubium** [comment]
> Oh, I would advise using IntelliJ for such task, as it will require testing to be done properly, I am unsure if it can run on a chromebook though.

It can, but I'm not allowed to turn on Linux mode needed to run it. I'll draft this pr until i get home.

**Comment by Koud-Wind** [comment]
My solution:
If HudTextureName is Marine,
The following code won't execute

\weaponlib\CustomGui.java
GL11.glPushAttrib(GL11.GL_ALL_ATTRIB_BITS);
GL11.glColor4f(1.0F, 1.0F, 1.0F, 1.0F);
GL11.glDisable(GL11.GL_LIGHTING);
GL11.glBlendFunc(GL11.GL_SRC_ALPHA, GL11.GL_ONE_MINUS_SRC_ALPHA);
GL11.glEnable(GL11.GL_BLEND);
mc.renderEngine.bindTexture(new ResourceLocation(hudTexture));
drawTexturedQuadFit(0, 0, screenWidth, screenHeight, -100);
GL11.glPopAttrib();

**Comment by Desoroxxx** [comment]
> My solution: If HudTextureName is Marine, The following code won't execute
> 
> \weaponlib\CustomGui.java GL11.glPushAttrib(GL11.GL_ALL_ATTRIB_BITS); GL11.glColor4f(1.0F, 1.0F, 1.0F, 1.0F); GL11.glDisable(GL11.GL_LIGHTING); GL11.glBlendFunc(GL11.GL_SRC_ALPHA, GL11.GL_ONE_MINUS_SRC_ALPHA); GL11.glEnable(GL11.GL_BLEND); mc.renderEngine.bindTexture(new ResourceLocation(hudTexture)); drawTexturedQuadFit(0, 0, screenWidth, screenHeight, -100); GL11.glPopAttrib();

No let just stick with basic Java conventions, and clean code principles.

**Comment by Desoroxxx** [comment]
Done in #130

**Pull request closed without merging**
