### PR TITLE
The license update no one asked for

### PR DESCRIPTION
**Pull request by strubium**
And yes, anything in the APPENDIX is not required.

### CODE REVIEW

**Comment by strubium** [comment]
> License update is nice.
> 
> But please remove the change from `>` to `<i>`

Done!

**Comment by Desoroxxx** [comment]
Huh, somehow the spaces got removed?

**Comment by Desoroxxx** [comment]
Fine, I did it myself moment.

**Comment by strubium** [comment]
> Fine I did it myself moment.

lamo

**Pull request merged**
