### PR TITLE
Fixing visual optimization bugs

### PR DESCRIPTION
**Pull request by Braiam23**
## 🤔 What type of PR is this? (check all applicable)

- [X] 🍕 Addition
- [ ] ⌨️ Productivity
- [X] 🐛 Bug Fix
- [ ] 🔥 Optimization
- [ ] ⚙️ Configuration
- [ ] 🌟 Quality Of Life
- [ ] ✨ Enhancement
- [ ] 📝 Documentation

## 📝 Description

After the optimization, it seems that several visual bugs were caused, luckily most of them can be fixed.

## 🎯 Key Objectives

Fix the damn bugs, this mod looks like Call of Duty for each fix or optimization the mod breaks more

## 🚦 Testing 

Yep everything is tested before uploading this to the branch
Note: It is not necessary to make a Changelog because this should not happen. It is supposed that after the optimization the mod should remain intact, not cause more bugs._.

## 📖 Added to documentation?

- [ ] 📜 README.md
- [ ] 📓 Javadoc
- [ ] 🍕 Comments
- [X] 🙅 no documentation needed

No me voy ir con el trabajo a medio hacer :v

### CODE REVIEW

**Comment by Desoroxxx** [comment]
This will be merged after the rendering rewrite I hope most of it can be keeped through it

**Comment by Braiam23** [comment]
> This will be merged after the rendering rewrite I hope most of it can be keeped through it

I mean, how did I not understand?

**Comment by Desoroxxx** [comment]
> > This will be merged after the rendering rewrite I hope most of it can be keeped through it
> 
> how did I not understand?

The rendering is currently being rewritten

**Comment by Braiam23** [comment]
> The rendering is currently being rewritten

I really did not understand, but if there is a way to solve it, I can try everything

**Comment by Desoroxxx** [comment]
> > The rendering is currently being rewritten
> 
> I really did not understand, but if there is a way to solve it, I can try everything

The entire rendering code is getting rewritten a lot of things will/may changes, a lot as been done already, so things may conflicts but I will try to handle the conflicts don't worry

**Comment by Braiam23** [comment]
ok sorry for bothering

**Comment by Koud-Wind** [comment]
Some guns undergo cartridge replacement after changing their sleeves, but they will not change. Can you help me repair them?
Just like this
image

**Comment by Koud-Wind** [comment]
Some guns undergo cartridge replacement after changing their sleeves, but they will not change. Can you help me repair them?
Just like this
image

**Comment by Braiam23** [comment]
> Some guns undergo cartridge replacement after changing their sleeves, but they will not change. Can you help me repair them? Just like this image

how do you fix that?

**Comment by Koud-Wind** [comment]
image

**Pull request closed without merging**
