### PR TITLE
Adjusting weapon order

### PR DESCRIPTION
**Pull request by Koud-Wind**

### CODE REVIEW

**Comment by Desoroxxx** [comment]
Have you tested all possible cases, I am concerned by this comment:
`Try not to change the order of the guns to ensure stable recipes`

**Comment by Koud-Wind** [comment]
Let me give an example: I have created a new world1 and have an M200 that I have modified. The order of weapons in my world2 is different. I want to transfer the M200 to my world2, but it may crash directly because NBT is not interconnected
If I have a World3 with the same weapon order as World1, then I can transfer M200 to World3
Every world that has used VMW has its weapons in a disordered order, and currently few people do it like me

**Comment by Koud-Wind** [comment]
> Try not to change the order of the guns to ensure stable recipes

This is not inherently stable

**Comment by Koud-Wind** [comment]
For most people, it don't

**Comment by Desoroxxx** [comment]
> For most people, it don't

In what case will it cause problems?

**Comment by Koud-Wind** [comment]
image

**Review by Desoroxxx — APPROVED** [review]
Sure

**Pull request merged**
