### PR TITLE
Configurable bullet break and penetration

### PR DESCRIPTION
**Pull request by Koud-Wind**
## 🤔 What type of PR is this? (check all applicable)

- [ ] 🍕 Addition
- [ ] ⌨️ Productivity
- [ ] 🐛 Bug Fix
- [x] 🔥 Optimization
- [x] ⚙️ Configuration
- [ ] 🌟 Quality Of Life
- [ ] ✨ Enhancement
- [ ] 📝 Documentation

## 🚦 Testing 
√

## 📖 Added to documentation?

- [ ] 📜 README.md
- [ ] 📓 Javadoc
- [ ] 🍕 Comments
- [x] 🙅 no documentation needed

### CODE REVIEW

**Comment by Paneedah** [comment]
Misclick ffs mobile app is crap

**Comment by Desoroxxx** [comment]
Material checking should be prioritized, before block checking.

This would break compatibility with glass things from mod.

I greatly recommend just closing this and waiting for the new config system to be implemented which as very intuitive and easy system for configurable materials blacklist/whitelist.

**Comment by Koud-Wind** [comment]
Some mod blocks are made of glass, but some players may not want them to be damaged/penetrated, such as bulletproof glass blocks

**Comment by Desoroxxx** [comment]
> Some mod blocks are made of glass, but some players may not want them to be damaged/penetrated, such as bulletproof glass blocks

That is why this should wait for the new config system which will have blacklist

**Pull request closed without merging**
