### PR TITLE
Rendering rewrite

### PR DESCRIPTION
**Pull request by Desoroxxx**
## 🤔 What type of PR is this?

- [ ] 🍕 Addition
- [X] ⌨️ Productivity
- [X] 🐛 Bug Fix
- [X] 🔥 Optimization
- [ ] ⚙️ Configuration
- [X] 🌟 Quality Of Life
- [ ] ✨ Enhancement
- [ ] 📝 Documentation

## 📝 Description

This rewrite rendering of basically everything

## 🧐 The Rationale

Rendering is convoluted and way to complex for not much

## 🎯 Key Objectives

- Simplify rendering
- Cleanup the code
- Fix issues like the animation's differences between the game and Blockbench
- Fix compatibility with mods and possibly shaders
- Make placements of everything easier

## 🚦 Testing 

Run client

## ⏮️ Backwards Compatibility 

This is rendering so there is no concern plus we still don't have a version out 

## 📖 Added to documentation?

- [ ] 📜 README.md
- [x] 📓 Javadoc
- [x] 🍕 Comments
- [ ] 🙅 no documentation needed

### CODE REVIEW

**Comment by notdeadpool456** [comment]
Isnt equipments an error since its a noncount noun.

**Comment by strubium** [comment]
> Isnt equipments an error since its a noncount noun.

#259

**Comment by Desoroxxx** [comment]
> Isnt equipments an error since its a noncount noun.

This isn't really about grammar it's about package naming conventions

**Comment by notdeadpool456** [comment]
> > Isnt equipments an error since its a noncount noun.
> 
> This isn't really about grammar it's about package naming conventions

Right but why make them confusing?

**Comment by Desoroxxx** [comment]
> > > Isnt equipments an error since its a noncount noun.
> > 
> > 
> > This isn't really about grammar it's about package naming conventions
> 
> Right but why make them confusing?

It's not confusing, if you know and follow the Java conventions equipment with no S would be confusing, weapon is a class weapons is a package containing weapon's

**Comment by strubium** [comment]
> > > > Isnt equipments an error since its a noncount noun.
> > > 
> > > 
> > > This isn't really about grammar it's about package naming conventions
> > 
> > 
> > Right but why make them confusing?
> 
> It's not confusing, if you know and follow the Java conventions equipment with no S would be confusing, weapon is a class weapons is a package containing weapon's

Then whyd you change the lang for the equipment creative tab? Or are you just covering your ass?

**Comment by Desoroxxx** [comment]
> Then whyd you change the lang for the equipment creative tab? Or are you just covering your ass?

Because the lang isn't a package name or a class????

**Comment by strubium** [comment]
> > Then whyd you change the lang for the equipment creative tab? Or are you just covering your ass?
> 
> Because the lang isn't a package name or a class????

Exactly, why did you change it?

**Comment by Desoroxxx** [comment]
> Exactly, why did you change it?

Because I used English conventions instead of Java ones since they are not Java related names???

**Comment by strubium** [comment]
> > Exactly, why did you change it?
> 
> Because I used English conventions instead of Java ones since they are not Java related names???

What the f is a "English convention" i switch it to a word that doesn't exist

**Comment by Desoroxxx** [comment]
> What the f is a "English convention" you switched it to a word that doesn't exist

If you mean that it's named equipments in the lang file it's called reckless refactoring, sadly something that can't be avoided on this project for multiple reasons, this kind of reckless refactoring would have been fixed as it's obviously a reckless refactor as you can see from the constant being correct and the id not being correct, but sadly it isn't fixed since equipment overhaul is on pause while the rendering rewrite is happening

**Comment by Desoroxxx** [comment]
GitHub is being reworked, please reopen this pull request once finished, will update on Discord once the rework is done.

**Pull request closed without merging**
