### PR TITLE
Fix hitbox's & Make Airdrop not give loot.

### PR DESCRIPTION
**Pull request by strubium**
## 🤔 What type of PR is this? (check all applicable)

- [ ] 🍕 Addition
- [ ] ⌨️ Productivity
- [x] 🐛 Bug Fix
- [ ] 🔥 Optimization
- [ ] ⚙️ Configuration
- [ ] 🌟 Quality Of Life
- [ ] ✨ Enhancement
- [ ] 📝 Documentation

## 📝 Description

Self-explanatory,   

## 🧐 The Rationale

I'm using the MWC props for deco in builds for a server I dev, and many props have the default hitbox which makes them hard to be used.

I know the props are gonna be changed and moved to another mod, but until then.

## 🎯 Key Objectives

- Remove old contagion code
- Give the radio a new hitbox (Uses the small weapons case's hitbox while I learn to use AxisAlignedBB)
- Give Locker and SCP Locker hitboxes

## ⏮️ Backwards Compatibility 

1.12.2

## 📚 Related Issues & Documents

N/A

## 🖼️ Screenshots/Recordings

N/a

## 📖 Added to documentation?

- [ ] 📜 README.md
- [ ] 📓 Javadoc
- [ ] 🍕 Comments
- [x] 🙅 no documentation needed

### CODE REVIEW

**Comment by Desoroxxx** [comment]
I really appreciate the work you're doing there that's really cool, even though it is all going to be redone I am sure this is a change that will be enjoyed by many

**Comment by strubium** [comment]
Added new hitboxes for the Fridge (Open and Closed), new hitboxes for the Locker and SCP Locker, a new hitbox for the Dumpster, and a new half-hight hitbox for the sandbag. 

Plans:

- Fix Duel Flood Light hitbox
- Update Changelog
- Merge

**Comment by strubium** [comment]
Welp, all this needs is for yall to test it

**Comment by Desoroxxx** [comment]
Will take a look later today

**Comment by strubium** [comment]
Thank you

**Review by Desoroxxx — APPROVED** [review]

**Pull request merged**
