### PR TITLE
Fix player damage

### PR DESCRIPTION
**Pull request by Koud-Wind**

### CODE REVIEW

**Comment by Desoroxxx** [comment]
Please use the pr template, since now I have this question: What is the rationale behind this change?

**Comment by Koud-Wind** [comment]
The damage received from onLivingHurtEvent has been reduced through armor, and ISpecialArmor. ArmorProperties. applyArmor will then traverse the armor stack and calculate the reduction

**Comment by Desoroxxx** [comment]
> The damage received from onLivingHurtEvent has been reduced through armor, and ISpecialArmor. ArmorProperties. applyArmor will then traverse the armor stack and calculate the reduction

But how is that different than the current way of doing it

**Comment by Koud-Wind** [comment]
This does not use ISpecialArmor. ArmorProperties. applyArmor to calculate damage

**Comment by Koud-Wind** [comment]
Players can recall this change to prevent another disruption to the balance they have established themselves

**Comment by Desoroxxx** [comment]
> Players can recall this change to prevent another disruption to the balance they have established themselves

That doesn't answer my question

**Comment by Koud-Wind** [comment]
> ISpecialArmor. ArmorProperties. applyArmor

No, this monitor can only monitor the damage value after armor reduction, ISpecialArmor ArmorProperties.applyArmor will once again reduce and set the final damage taken by the player

**Comment by Desoroxxx** [comment]
What is the error you are mentioning in `Fix the damage error of players`?

**Comment by Koud-Wind** [comment]
Yes, this question is only for players

**Comment by Koud-Wind** [comment]
> I will look into it myself later this all seems weird and as I just said on Discord, I don't like adding config to every little things because it just kills it, player won't look for configs if the file is 800 lines long.

Is it inconvenient for testing? I can temporarily provide a testing server

**Comment by notdeadpool456** [comment]
This isnt even trivial diamond armor does massively overpowered damage reduction. To the point where going foward we've banned it on every geopol version since 3.0^2. Which it has been an issue since squared and for some reason has still not been changed. Whenever I present it to be rebalanced they tell me to make a balancepack (which cannot change armor effectiveness), and buffing gun damage creates a whole other can of worms of unbalanced features. Considering iron armor is relatively fine.

**Comment by notdeadpool456** [comment]
> This isnt even trivial diamond armor does massively overpowered damage reduction. To the point where going foward we've banned it on every geopol version since 3.0^2. Which it has been an issue since squared and for some reason has still not been changed. Whenever I present it to be rebalanced they tell me to make a balancepack (which cannot change armor effectiveness), and buffing gun damage creates a whole other can of worms of unbalanced features. Considering iron armor is relatively fine.

and yes I am talking about cubed when I say whenever I present it to be rebalanced

**Comment by Koud-Wind** [comment]
> This isnt even trivial diamond armor does massively overpowered damage reduction. To the point where going foward we've banned it on every geopol version since 3.0^2. Which it has been an issue since squared and for some reason has still not been changed. Whenever I present it to be rebalanced they tell me to make a balancepack (which cannot change armor effectiveness), and buffing gun damage creates a whole other can of worms of unbalanced features. Considering iron armor is relatively fine.

After merging, this issue will be fixed

**Comment by Desoroxxx** [comment]
Yeah but no, the fix is not to make a config, the real thing is to change how we calculate damage reduction in a better way

**Comment by notdeadpool456** [comment]
> Yeah but no, the fix is not to make a config, the real thing is to change how we calculate damage reduction in a better way

I agree maybe even both. The damage reduction shouldn't be this broken by default.

**Comment by Koud-Wind** [comment]
> Yeah but no, the fix is not to make a config, the real thing is to change how we calculate damage reduction in a better way

Didn't I already solve it?

**Comment by Desoroxxx** [comment]
Well maybe but I don't want this to be a config and I don't want a half full half empty glass I want to find the best solution I don't know if this is it or not yet.

One thing is sure is that it shouldn't be a config so you can already remove the configurability out of it

**Comment by Paneedah** [comment]
> 

Ah yeah. This bug was always fun. Basically wearing any armour (e.g. diamond armour) with VMW would make you invincible which is hilarious! I made a server-side mod before as a fix to just block mixing armours between vmw and any other mod xD

**Comment by Koud-Wind** [comment]
> Well maybe but I don't want this to be a config and I don't want a half full half empty glass I want to find the best solution I don't know if this is it or not yet.
> 
> One thing is sure is that it shouldn't be a config so you can already remove the configurability out of it

Initiate a vote?

**Comment by Desoroxxx** [comment]
> > Well maybe but I don't want this to be a config and I don't want a half full half empty glass I want to find the best solution I don't know if this is it or not yet.
> > One thing is sure is that it shouldn't be a config so you can already remove the configurability out of it
> 
> Initiate a vote?

What vote, just remove the configuration part, like fix it without making it a config

**Comment by Koud-Wind** [comment]
I just think that such changes will break the established balance of PVP servers

**Comment by Desoroxxx** [comment]
Have you tested this in Multiplier? How does it behave compared to the old method, not only relating to armor, but just in general what changed?

**Comment by Koud-Wind** [comment]
√

**Comment by Desoroxxx** [comment]
> √

That is not an anwser

**Comment by strubium** [comment]
> √

Is that a check? i think its a check

**Comment by Koud-Wind** [comment]
I test every merger, I mentioned above that ispecialarmor.Armor.Properties. applyArmor is the key to the mistake.

**Comment by Desoroxxx** [comment]
> > √
> 
> Is that a check? i think its a check

But it does not answer my question which is what changes can be obvesrved when PVPing and when PVEing

**Comment by Koud-Wind** [comment]
> > > √
> > 
> > 
> > Is that a check? i think its a check
> 
> But it does not answer my question which is what changes can be obvesrved when PVPing and when PVEing

This is only about calculating damage reduction based on whether the player is wearing bulletproof vests, PVEing will not be calculated here

**Comment by Desoroxxx** [comment]
Wait @Koud-Wind does this still take in count armor apart from vest?

**Comment by Koud-Wind** [comment]
The incoming damage has been reduced by armor.

**Comment by Desoroxxx** [comment]
> The incoming damage has been reduced by armor.

But like vanilla armor not mwc vests

**Comment by Koud-Wind** [comment]
Yes, I'm talking about vanilla armor，The mwc vest will also

**Comment by Koud-Wind** [comment]
livingHurtEvent.setAmount((float) (livingHurtEvent.getAmount() * (1 - ((ItemVest) DamageBlocked).getDamageBlocked())));

**Pull request merged**
