### PR TITLE
Generate major repairs

### PR DESCRIPTION
**Pull request by Koud-Wind**
## 🤔 What type of PR is this? (check all applicable)

- [ ] 🍕 Addition
- [ ] ⌨️ Productivity
- [x] 🐛 Bug Fix
- [x] 🔥 Optimization
- [x] ⚙️ Configuration
- [ ] 🌟 Quality Of Life
- [ ] ✨ Enhancement
- [ ] 📝 Documentation

## 📝 Description
Fixed configuration (bandit&soldier health/generation rate) and cleaned up some code
This is the third submission, I don't know if it meets your requirements

## 🚦 Testing 
 - [ ] Server
 - [x] Client
 - [ ] Client and server testing for other computers

### CODE REVIEW

**Comment by Desoroxxx** [comment]
This is not really a step in the good direction you took out hot reloadability

**Comment by Koud-Wind** [comment]
> This is not really a step in the good direction you took out hot reloadability

But this at least fixed the problem of bandits and soldiers generating

**Comment by Desoroxxx** [comment]
Yeah but it needs to be fixed without making the config worst

**Comment by Koud-Wind** [comment]
Waiting for my further improvement.

**Comment by Koud-Wind** [comment]
This seems to be unable to hot reload, as entities cannot be changed at the moment the game is launched

**Comment by Koud-Wind** [comment]
@Desoroxxx If this is feasible, I will soon merge it

**Comment by Desoroxxx** [comment]
> Accept the invite I sent you, just realized Paneedah never added you...
> 
> Anyway accept it and you will be able to create branch on **this repo** no need for your fork anymore

Please do this, I want to test this before any kind of review

**Comment by Koud-Wind** [comment]
> > Accept the invite I sent you, just realized Paneedah never added you...
> > Anyway accept it and you will be able to create branch on **this repo** no need for your fork anymore
> 
> Please do this, I want to test this before any kind of review

I know, I will do this next time I make changes

**Comment by Desoroxxx** [comment]
Yeah but:
1. This is not up to date with Master
2. I can't test it without it being a branch

**Pull request closed without merging**
