### PR TITLE
Give Vests Durability 

### PR DESCRIPTION
**Pull request by strubium**
Should help with balance.

### CODE REVIEW

**Comment by Desoroxxx** [comment]
For me it's a yes, for now, in the overhaul they will be changed but for now it's a good compromise

**Comment by Desoroxxx** [comment]
bruh

**Comment by Desoroxxx** [comment]
At least fix it before merging...

Now I need to change branch, sync, open it, find it and fix it...

**Comment by SticksDeveloper** [comment]
> bruh

Indeed bruh vests don't need durability especially this low

**Comment by strubium** [comment]
> Indeed bruh vests don't need durability especially this low

Vests act like armor so they should have durability like armor. And now the values are really easy to tweak.

**Pull request merged**
