### PR TITLE
Fix missing sounds

### PR DESCRIPTION
**Pull request by strubium**
## 📝 Description

Fixes some sounds not being added to UniversalSoundLookup, and therefore not playing. This was discovered by @Braiam23 on their [fork](https://github.com/Braiam23/Modern-Warfare-Cubed--Extra-Content).

## 🎯 Goals

- Greatly improve the sounds when reloading revolver's, the m200, and the m40a6

## ❌ Non Goals

- Break the mod
- Add new sounds 

## 🚦 Testing 

Ye ye

## ⏮️ Backwards Compatibility 

1.12.2

## 📚 Related Issues & Documents

https://github.com/Braiam23/Modern-Warfare-Cubed--Extra-Content/blob/main/src/main/java/com/paneedah/mwc/UniversalSoundRegistry.java 

## 🖼️ Screenshots/Recordings

N/A

## 📖 Added to documentation?

- [ ] 📜 README.md
- [ ] 📑 Documentation
- [ ] 📓 Javadoc
- [ ] 🍕 Comments
- [x] 🙅 No documentation needed

### CODE REVIEW

**Review by Desoroxxx — APPROVED** [review]

**Review by Desoroxxx — CHANGES_REQUESTED** [review]
Changelog

**Comment by strubium** [comment]
> Changelog

done

**Review by Desoroxxx — APPROVED** [review]
LGTM

**Review by Desoroxxx — APPROVED** [review]
LGTM lol

**Pull request merged**
