### PR TITLE
Fix issue with M76 Frag Grenade not exploding in player's hand when cooked

### LINKED ISSUE #306: M67 Frag Grenade does not explode in hand
## Describe the bug
When cooking an M67 Frag Grenade, it does not explode in the player's hand once the fuse has run out, instead throwing the error in the logs below.

## Reproducibility
Please try to reproduce the issue with as few other mods as possible. Then check one of the following checkboxes according to your results. To check a checkbox, replace the space between the square brackets with an x (like this [x]) or create the issue and check the checkbox by clicking on it.

- [x] I reproduced this issue with as few other mods as possible installed.
- [x] I am unable to reproduce this issue consistently.

## To Reproduce

1. Select M67 Frag Grenade
2. Right click to start fuse
3. Wait until fuse runs out
4. See error in console

## Expected behavior

Grenade explodes in player's hand.

## Screenshots or/and videos
https://github.com/Cubed-Development/Modern-Warfare-Cubed/assets/32090502/94de637e-0eaa-4d98-9095-2a9f2520a70a

## Logs or/and crash reports
https://mclo.gs/IxSpJF9

## Versions

- Modern Warfare Cubed: MWC-0.1-Dev-14
- Forge: 1.12.2 - 14.23.5.2859
- Java: JDK 8 - 392-392
- Java JVM: Unknown

## Specification:

- OS: Windows 10
- CPU: AMD Ryzen 5 3400G
- GPU: NVIDIA GeForce RTX 3050
- RAM Allocated: 16GB

### PR DESCRIPTION
**Pull request by MCT32**
## 🤔 What type of PR is this? (check all applicable)

- [ ] 🍕 Addition
- [ ] ⌨️ Productivity
- [x] 🐛 Bug Fix
- [ ] 🔥 Optimization
- [ ] ⚙️ Configuration
- [ ] 🌟 Quality Of Life
- [ ] ✨ Enhancement
- [ ] 📝 Documentation

## 📝 Description

This PR fixes issue #306 

## 🧐 The Rationale

This makes the grenade behave as expected and intended.

## 🎯 Key Objectives

Fix the issue

## 🚦 Testing 

Repeated the steps in the issue with changes and problem was solved.

## ⏮️ Backwards Compatibility 

Should be

## 📚 Related Issues & Documents

Fixes #306 

## 🖼️ Screenshots/Recordings

https://github.com/Cubed-Development/Modern-Warfare-Cubed/assets/32090502/5077be4d-9be9-48c7-9670-fb894235c670

## 📖 Added to documentation?

- [ ] 📜 README.md
- [ ] 📓 Javadoc
- [ ] 🍕 Comments
- [x] 🙅 no documentation needed

## 😄 [optional] What gif best describes this PR or how it makes you feel?

img

### CODE REVIEW

**Comment by Desoroxxx** [comment]
Grenade blowing in hand is being removed, so this pr does not address the issue correctly

**Comment by MCT32** [comment]
Is the intended behavior of the grenade not to explode after the fuse runs out? The code for the grenade attempts to create an explosion but fails because of improper parameters. If the grenade is not meant to explode i can remove the failed explosion function from the grenade.

**Comment by Desoroxxx** [comment]
> Is the intended behavior of the grenade not to explode after the fuse runs out?

Yes that is how a grenade works

**Comment by MCT32** [comment]
So why is the grenade exploding in the players hand being removed?

**Comment by Desoroxxx** [comment]
> So why is the grenade exploding in the players hand being removed?

Because grenades don't explode in your hand, you have to let go of the safety lever

**Pull request closed without merging**
