### PR TITLE
Fix Drum Mag and Sight M5 texture issues

### PR DESCRIPTION
**Pull request by Braiam23**
## 🤔 What type of PR is this? (check all applicable)

- [ ] 🍕 Addition
- [ ] ⌨️ Productivity
- [X] 🐛 Bug Fix
- [ ] 🔥 Optimization
- [ ] ⚙️ Configuration
- [ ] 🌟 Quality Of Life
- [X] ✨ Enhancement
- [ ] 📝 Documentation

## 📝 Description
I have tested the changes that I made to the models of the chargers and well, it does not work correctly due to the name of the texture and the magazine.java modification

## 🚦 Testing 

image
texture problems ;p
IT'S FIXED NOW :D
image

## 📖 Added to documentation?

- [X] 📜 README.md
- [ ] 📓 Javadoc
- [ ] 🍕 Comments
- [ ] 🙅 no documentation needed

NOTE: it only accepts the last 3 changes, the ones of this day, the previous ones I have not tested and they may have bugs and remove the "Drum100rndMag.png" texture and keep the new "drum100rndmag.png"

"fix and improve texture" "Fix texture 100rnd Drum Mag" "Better Model Drum mag fix z-fighting"

### CODE REVIEW

**Comment by Paneedah** [comment]
Please resolve conflicts and it looks good to merge as soon as that's done. Will allow for @Desoroxxx to review as well before merging.

**Comment by Braiam23** [comment]
um.. that's weird, I didn't touch almost anything in the mod, I only touched some parts of the magazine.java code

**Comment by Braiam23** [comment]
@Desoroxxx It is possible to solve this pull request conflict problem? or if there is no solution, revert the previous changes

**Comment by Desoroxxx** [comment]
I will look into it soon

**Comment by Braiam23** [comment]
please revert all model changes and keep animation improvements from m40a6

**Pull request closed without merging**
