### PR TITLE
More Prop Fixes (Fixes the Dumpster)

### PR DESCRIPTION
**Pull request by strubium**
## 🤔 What type of PR is this? (check all applicable)

- [ ] 🍕 Addition
- [ ] ⌨️ Productivity
- [x] 🐛 Bug Fix
- [ ] 🔥 Optimization
- [ ] ⚙️ Configuration
- [x] 🌟 Quality Of Life
- [ ] ✨ Enhancement
- [ ] 📝 Documentation

## 📝 Description

Fixes more hitboxes

## 🧐 The Rationale

See other PR's

## ⏮️ Backwards Compatibility 

1.12.2

## 📖 Added to documentation?

- [ ] 📜 README.md
- [ ] 📓 Javadoc
- [ ] 🍕 Comments
- [x] 🙅 no documentation needed

### CODE REVIEW

**Comment by Desoroxxx** [comment]
Why is this named `(Fixes the Dumpster)` when it fixes other props than the dumpster was this meant to be a draft?

**Comment by strubium** [comment]
> Why is this named `(Fixes the Dumpster)` when it fixes other props than the dumpster was this meant to be a draft?

If you scroll to about line 877, you'll see edits for the dumpster prop. I goofed and forgot to rotate the hitbox.

**Comment by Desoroxxx** [comment]
Then you forgot to add it to the changelog

**Comment by strubium** [comment]
It was already in the changelog 
- Fixed prop hitboxes not lining up with their models:
  - Fridge (open/closed)
  - Locker
  - SCP Locker
  - **Dumpster**
  - Sandbag
  - Duel Floodlight
  - Single Floodlight
  - Shelf Top
  - Server Rack Top
  - Laptop
  - Desk Shelf
  - Desk Shelf (Alt2)
  - Impaled Body

**Review by Desoroxxx — APPROVED** [review]
What a dumpster fire 😅

**Pull request merged**
