### PR TITLE
Headshot repair

### PR DESCRIPTION
**Pull request by Koud-Wind**
## 🤔 What type of PR is this? (check all applicable)

- [ ] 🍕 Addition
- [ ] ⌨️ Productivity
- [x] 🐛 Bug Fix
- [x] 🔥 Optimization
- [ ] ⚙️ Configuration
- [ ] 🌟 Quality Of Life
- [x] ✨ Enhancement
- [ ] 📝 Documentation

## 📝 Description
Getting the headshot back to work
Better cancellation of knockback
Enhanced compatibility of bullets 
A death message similar to an arrow
Restore Changes https://github.com/Cubed-Development/Modern-Warfare-Cubed/commit/57991d5a59f86b10c477e8cf030530e71da81529#diff-45732871cf83ed288fa7a477f53d5f8f4e7cc982e15b100c6ccd3b2fc63ca9dc

## 🚦 Testing 
 - [x] Client
 - [ ] Server

## 🖼️ Screenshots/Recordings
https://cdn.discordapp.com/attachments/1078839351468892241/1140491383745020006/Base_Profile_2023.08.14_-_11.44.00.03.mp4
https://cdn.discordapp.com/attachments/1078839351468892241/1140492934769291354/Base_Profile_2023.08.14_-_11.50.26.05.mp4

image

### CODE REVIEW

**Comment by Desoroxxx** [comment]
Again, we are not adding the headshot back

**Comment by Desoroxxx** [comment]
I removed it because it is super stupid, don't add back the same stupid headshot system

**Comment by Koud-Wind** [comment]
> I removed it because it is bad, don't add back the same bad headshot system

Players may be very concerned about the headshot, and I think we cannot hastily delete it. It will change players' gaming habits, and we will come back to change it when we find a better way to headshot

**Comment by Desoroxxx** [comment]
> > I removed it because it is bad, don't add back the same bad headshot system
> 
> Players may be very concerned about the headshot, and I think we cannot hastily delete it. It will change players' gaming habits, and we will come back to change it when we find a better way to headshot

But currently the headshot isn't a headshot, it does not work, everything except the legs count as a headshot

**Comment by Desoroxxx** [comment]
Also the change to entity arrow is a bad one

**Pull request closed without merging**
