### PR TITLE
Create zh_CN.lang

### PR DESCRIPTION
**Pull request by ChromaPIE**
Locale for Simplified Chinese

### CODE REVIEW

**Comment by Desoroxxx** [comment]
Hey, this is a draft PR, was that by accident or is there something you would like to improve?

Otherwise I can merge it now.

**Comment by ChromaPIE** [comment]
@Desoroxxx nah bc its not finished yet, and also in case of possible changes on the en_us lang.

**Comment by Koud-Wind** [comment]
A neat translation, I have a suggestion that you can add the weapon type after the weapon name

**Comment by DreamSky7** [comment]
类型应该写在lore上更合适吧

**Comment by DreamSky7** [comment]
It should be more appropriate to put it in Lore.

**Comment by Paneedah** [comment]
I didn't mean to click that.

**Comment by Desoroxxx** [comment]
Hey is this ready or should this be put back as a draft?

**Comment by Koud-Wind** [comment]
> Hey is this ready or should this be put back as a draft?

https://github.com/Cubed-Development/Modern-Warfare-Cubed/pull/79

**Pull request closed without merging**
