### PR TITLE
Removal of Props to move to the Props mod

### PR DESCRIPTION
**Pull request by SticksDeveloper**
Removal of props to move to the props mod before 0.1

### CODE REVIEW

**Comment by Paneedah** [comment]
What's the reason of this being a draft? Did you not remove them all?

**Comment by Desoroxxx** [comment]
> What's the reason of this being a draft? Did you not remove them all?

It's a draft because they will only be removed when the props mod is a thing

**Comment by Paneedah** [comment]
Okay that makes sense.

**Comment by Desoroxxx** [comment]
That and the fact that this only remove the registering of them

**Pull request closed without merging**
