### PR TITLE
m1014, Supernova

### PR DESCRIPTION
**Pull request by notdeadpool456**
These guns are not really broken from what I've seen, and it would be a nice addition.

### CODE REVIEW

**Comment by SticksDeveloper** [comment]
Actually not bad

**Comment by SticksDeveloper** [comment]
Nevermind github moment

**Comment by notdeadpool456** [comment]
I've tested it ingame and it works as expected.

**Review by strubium — APPROVED** [review]

**Comment by Desoroxxx** [comment]
Thanks, will be a nice addition!

**Pull request merged**
